# Generated by Django 6.0.2 on 2026-02-21 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='savedreport',
            options={'ordering': ['-is_pinned', '-created_at']},
        ),
        migrations.AddField(
            model_name='savedreport',
            name='is_pinned',
            field=models.BooleanField(default=False),
        ),
    ]
